// Generated by https://quicktype.io

export interface AuthLoginResponse {
    nombre:             string;
    apellidos:          string;
    username:           string;
    email:              string;
    fotoPerfil:         string;
    rol:                string;
    token:              string;
    privacidad:         string;
    listaPublicaciones: any[];
}
