// Generated by https://quicktype.io

export interface PostsResponse {
    content:          Posts[];
    pageable:         Pageable;
    last:             boolean;
    totalElements:    number;
    totalPages:       number;
    size:             number;
    number:           number;
    sort:             Sort;
    first:            boolean;
    numberOfElements: number;
    empty:            boolean;
}

export interface Posts {
    id:              string;
    titulo:          string;
    texto:           string;
    fichero:         string;
    privacidad:      string;
    usernameUsuario: string;
    fotoUsuario:     string;
}

export interface Pageable {
    sort:       Sort;
    offset:     number;
    pageSize:   number;
    pageNumber: number;
    paged:      boolean;
    unpaged:    boolean;
}

export interface Sort {
    empty:    boolean;
    unsorted: boolean;
    sorted:   boolean;
}
